-- This file generated by generate.py.

-- <yaml>
-- DependsOn: {}
-- </yaml>
SELECT  CAST(vs."_id" AS VARCHAR)      AS "_id",
        vs."assignee"                  AS "assignee",
        vs."closed_date"               AS "closed_date",
        vs."converted_date"            AS "converted_date",
        vs."evg_projects"              AS "evg_projects",
        vs."first_team_assigned_date"  AS "first_team_assigned_date",
        vs."is_release_blocker"        AS "is_release_blocker",
        vs."key"                       AS "key",
        vs."resolution"                AS "resolution",
        vs."score"                     AS "score",
        vs."severity"                  AS "severity",
        vs."status"                    AS "status",
        vs."team"                      AS "team",
        vs."time_buildbaron_triage"    AS "time_buildbaron_triage"
        -- <COMMON_ETL_FIELDS>
        , LOCALTIMESTAMP AS "_extract_timestamp"
        -- </COMMON_ETL_FIELDS>
FROM  "tpm_build_failures_atlas"."buildfailures"."bf" AS vs

