-- This file generated by generate.py.

-- <yaml>
-- DependsOn: {}
-- </yaml>
SELECT  CAST(vs."_id" AS VARCHAR)          AS "_id",
        vs."bfgqueueanalyzed"              AS "bfgqueueanalyzed",
        vs."bfgsanalyzed"                  AS "bfgsanalyzed",
        vs."bfgscreated"                   AS "bfgscreated",
        vs."bfgsprocessed"                 AS "bfgsprocessed",
        vs."bfqueuetriaged"                AS "bfqueuetriaged",
        vs."bfsclosedfromwfbf"             AS "bfsclosedfromwfbf",
        vs."bfsclosednotwfbf"              AS "bfsclosednotwfbf",
        vs."bfscreated"                    AS "bfscreated",
        vs."bfsengagedvscreated"           AS "bfsengagedvscreated",
        vs."bfsinvestigated"               AS "bfsinvestigated",
        vs."bfsmovedtostuck"               AS "bfsmovedtostuck",
        vs."bfsmovedtotrivial"             AS "bfsmovedtotrivial",
        vs."bfsmovedtowfbf"                AS "bfsmovedtowfbf",
        vs."bfsopen"                       AS "bfsopen",
        vs."bfstriaged"                    AS "bfstriaged",
        vs."botanalysislaghours"           AS "botanalysislaghours",
        vs."category"                      AS "category",
        vs."enddate"                       AS "enddate",
        vs."investigationtimedays"         AS "investigationtimedays",
        vs."processinglagdays"             AS "processinglagdays",
        vs."processinglaghours"            AS "processinglaghours",
        vs."startdate"                     AS "startdate",
        vs."stuckinvestigationtimedays"    AS "stuckinvestigationtimedays",
        vs."timetoclose"                   AS "timetoclose",
        vs."triagetimedays"                AS "triagetimedays",
        vs."triagetimehours"               AS "triagetimehours",
        vs."trivialinvestigationtimedays"  AS "trivialinvestigationtimedays",
        vs."typicalinvestigationtimedays"  AS "typicalinvestigationtimedays",
        vs."waitingtimeforfix"             AS "waitingtimeforfix"
        -- <COMMON_ETL_FIELDS>
        , LOCALTIMESTAMP AS "_extract_timestamp"
        -- </COMMON_ETL_FIELDS>
FROM  "tpm_build_failures_atlas"."buildfailures"."durations" AS vs

