-- This file generated by generate.py.

-- <yaml>
-- DependsOn: {}
-- </yaml>
SELECT  CAST(vs."_id" AS VARCHAR)  AS "_id",
        vs."_base_url"             AS "_base_url",
        vs."_options"              AS "_options",
        vs."_resource"             AS "_resource",
        vs."expand"                AS "expand",
        vs."fields"                AS "fields",
        vs."histories"             AS "histories",
        vs."id"                    AS "id",
        vs."key"                   AS "key",
        vs."self"                  AS "self"
        -- <COMMON_ETL_FIELDS>
        , LOCALTIMESTAMP AS "_extract_timestamp"
        -- </COMMON_ETL_FIELDS>
FROM  "tpm_build_failures_atlas"."coredb-patchbuild-optimizer"."server_data" AS vs

