-- This file generated by generate.py.

-- <yaml>
-- DependsOn: {}
-- </yaml>
SELECT  CAST(vs."_id" AS VARCHAR)        AS "_id",
        vs."aborted"                     AS "aborted",
        vs."activated"                   AS "activated",
        vs."activated_by"                AS "activated_by",
        vs."activated_time"              AS "activated_time",
        vs."ami"                         AS "ami",
        vs."api_version"                 AS "api_version",
        vs."artifacts"                   AS "artifacts",
        vs."blocked"                     AS "blocked",
        vs."build_id"                    AS "build_id",
        vs."build_variant"               AS "build_variant",
        vs."build_variant_display_name"  AS "build_variant_display_name",
        vs."create_time"                 AS "create_time",
        vs."dispatch_time"               AS "dispatch_time",
        vs."display_name"                AS "display_name",
        vs."display_only"                AS "display_only",
        vs."display_status"              AS "display_status",
        vs."distro_id"                   AS "distro_id",
        vs."est_wait_to_start_ms"        AS "est_wait_to_start_ms",
        vs."execution"                   AS "execution",
        vs."expected_duration_ms"        AS "expected_duration_ms",
        vs."finish_time"                 AS "finish_time",
        vs."generate_task"               AS "generate_task",
        vs."generated_by"                AS "generated_by",
        vs."host_id"                     AS "host_id",
        vs."ingest_time"                 AS "ingest_time",
        vs."logs"                        AS "logs",
        vs."mainline"                    AS "mainline",
        vs."must_have_test_results"      AS "must_have_test_results",
        vs."order"                       AS "order",
        vs."parent_task_id"              AS "parent_task_id",
        vs."priority"                    AS "priority",
        vs."project_id"                  AS "project_id",
        vs."project_identifier"          AS "project_identifier",
        vs."requester"                   AS "requester",
        vs."restarts"                    AS "restarts",
        vs."revision"                    AS "revision",
        vs."scheduled_time"              AS "scheduled_time",
        vs."start_time"                  AS "start_time",
        vs."status"                      AS "status",
        vs."status_details"              AS "status_details",
        vs."sync_at_end_opts"            AS "sync_at_end_opts",
        vs."task_id"                     AS "task_id",
        vs."time_taken_ms"               AS "time_taken_ms",
        vs."version_id"                  AS "version_id"
        -- <COMMON_ETL_FIELDS>
        , LOCALTIMESTAMP AS "_extract_timestamp"
        -- </COMMON_ETL_FIELDS>
FROM  patch_build_optimizer.evg.query_patch_version_task_data AS vs

