-- This file generated by generate.py.

-- <yaml>
-- DependsOn: {}
-- </yaml>
SELECT  CAST(vs."_id" AS VARCHAR)   AS "_id",
        vs."activated"              AS "activated",
        vs."activated_by"           AS "activated_by",
        vs."activated_time"         AS "activated_time",
        vs."actual_makespan_ms"     AS "actual_makespan_ms",
        vs."api_version"            AS "api_version",
        vs."build_variant"          AS "build_variant",
        vs."create_time"            AS "create_time",
        vs."display_name"           AS "display_name",
        vs."finish_time"            AS "finish_time",
        vs."git_hash"               AS "git_hash",
        vs."order"                  AS "order",
        vs."origin"                 AS "origin",
        vs."predicted_makespan_ms"  AS "predicted_makespan_ms",
        vs."project_id"             AS "project_id",
        vs."project_identifier"     AS "project_identifier",
        vs."start_time"             AS "start_time",
        vs."status"                 AS "status",
        vs."status_counts"          AS "status_counts",
        vs."time_taken_ms"          AS "time_taken_ms",
        vs."version"                AS "version"
        -- <COMMON_ETL_FIELDS>
        , LOCALTIMESTAMP AS "_extract_timestamp"
        -- </COMMON_ETL_FIELDS>
FROM  patch_build_optimizer_atlas.evg.query_patch_version_build_variant_data AS vs

