-- This file generated by generate.py.

-- <yaml>
-- DependsOn: {}
-- </yaml>
SELECT  CAST(vs."_id" AS VARCHAR)  AS "_id",
        vs."build_id"              AS "build_id",
        vs."build_variant"         AS "build_variant",
        vs."display_name"          AS "display_name",
        vs."duration"              AS "duration",
        vs."end_time"              AS "end_time",
        vs."execution"             AS "execution",
        vs."exit_code"             AS "exit_code",
        vs."logs"                  AS "logs",
        vs."start_time"            AS "start_time",
        vs."status"                AS "status",
        vs."task_id"               AS "task_id",
        vs."test_file"             AS "test_file",
        vs."test_id"               AS "test_id",
        vs."version"               AS "version"
        -- <COMMON_ETL_FIELDS>
        , LOCALTIMESTAMP AS "_extract_timestamp"
        -- </COMMON_ETL_FIELDS>
FROM  patch_build_optimizer.evg.version_test_data AS vs

