-- This file generated by generate.py.

-- <yaml>
-- DependsOn: {}
-- </yaml>
SELECT  CAST(vs."_id" AS VARCHAR)  AS "_id",
        vs."author"                AS "author",
        vs."author_email"          AS "author_email",
        vs."branch"                AS "branch",
        vs."commit"                AS "commit",
        vs."commit_date"           AS "commit_date",
        vs."evg_create_date"       AS "evg_create_date",
        vs."message"               AS "message",
        vs."repo_full_name"        AS "repo_full_name",
        vs."version_id"            AS "version_id"
        -- <COMMON_ETL_FIELDS>
        , LOCALTIMESTAMP AS "_extract_timestamp"
        -- </COMMON_ETL_FIELDS>
FROM  dev_prod_performance_atlas.expanded_metrics.versions AS vs

