-- https://docs.google.com/document/d/1SJ79dpCxRNt2lhLMfLeEuT4DVkwm_WymSmlqVymaM4Q/edit
-- mostly generated by various incantations in generator.py
select
    rank() over(partition by id order by _sdc_sequence desc) as rnk,
    nullif(nullif(fields__customfield_20550, 'nan'), 'None') as linked_major_incidents_cf, -- Linked major incidents
    nullif(nullif(fields__customfield_16851, 'nan'), 'None') as ts_on_screen_messaging_cf, -- TS On-Screen Messaging
    nullif(nullif(fields__customfield_18358, 'nan'), 'None') as product_manager_cf, -- Product Manager
    nullif(nullif(fields__customfield_10750, 'nan'), 'None') as steps_to_reproduce_cf, -- Steps To Reproduce
    nullif(nullif(fields__customfield_18359, 'nan'), 'None') as program_manager_cf, -- Program Manager
    nullif(nullif(fields__customfield_13450, 'nan'), 'None') as issuefunction_cf, -- issueFunction
    nullif(nullif(fields__customfield_19550, 'nan'), 'None') as issue_type_filters_security_managed_by_plugin__cf, -- Issue Type Filters Security (managed by plugin)
    cast(json_parse(nullif(nullif(fields__customfield_11150, 'nan'), 'None')) as array(row("self" varchar, "disabled" boolean, "id" varchar, "value" varchar))) as server_fixversion_cf, -- SERVER fixVersion
    nullif(nullif(fields__customfield_12360, 'nan'), 'None') as acceptance_criteria_cf, -- Acceptance Criteria
    nullif(nullif(fields__customfield_11151, 'nan'), 'None') as last_public_comment_date_cf, -- Last public comment date
    nullif(nullif(fields__customfield_13451, 'nan'), 'None') as author_cf, -- Author
    cast(json_parse(nullif(nullif(fields__customfield_13453, 'nan'), 'None')) as array(row("self" varchar, "disabled" boolean, "id" varchar, "value" varchar))) as technical_editor_cf, -- Technical Editor
    nullif(nullif(fields__customfield_21070, 'nan'), 'None') as time_to_assign_cf, -- Time to Assign
    nullif(nullif(fields__customfield_15751, 'nan'), 'None') as external_issue_id_cf, -- External issue ID
    cast(json_parse(nullif(nullif(fields__customfield_15756, 'nan'), 'None')) as array(varchar)) as failing_tests_cf, -- Failing Tests
    nullif(nullif(fields__customfield_10860, 'nan'), 'None') as epic_colour_cf, -- Epic Colour
    try(cast(nullif(nullif(fields__customfield_10855, 'nan'), 'None') as double)) as actual_time_cf, -- Actual Time
    try(cast(nullif(nullif(fields__customfield_10856, 'nan'), 'None') as double)) as original_estimate_cf, -- Original Estimate
    nullif(nullif(fields__customfield_10857, 'nan'), 'None') as epic_link_cf, -- Epic Link
    nullif(nullif(fields__customfield_10858, 'nan'), 'None') as epic_name_cf, -- Epic Name
    nullif(nullif(fields__customfield_10859, 'nan'), 'None') as epic_status_cf, -- Epic Status
    from_iso8601_date(nullif(nullif(fields__customfield_16150, 'nan'), 'None')) as last_review_cf, -- Last Review
    nullif(nullif(fields__customfield_17480, 'nan'), 'None') as time_to_approve_normal_change_cf, -- Time to approve normal change
    nullif(nullif(fields__customfield_12350, 'nan'), 'None') as release_announcement_cf, -- Release Announcement
    nullif(nullif(fields__customfield_10050, 'nan'), 'None') as _replies_cf, -- # Replies
    nullif(nullif(fields__customfield_10051, 'nan'), 'None') as participants_cf, -- Participants
    from_iso8601_date(nullif(nullif(fields__customfield_12352, 'nan'), 'None')) as target_date_cf, -- Target Date
    nullif(nullif(fields__customfield_10052, 'nan'), 'None') as days_since_reply_cf, -- Days since reply
    nullif(nullif(fields__customfield_12351, 'nan'), 'None') as tracking_url_cf, -- Tracking URL
    nullif(nullif(fields__customfield_10053, 'nan'), 'None') as time_in_status_cf, -- Time In Status
    from_iso8601_date(nullif(nullif(fields__customfield_16950, 'nan'), 'None')) as email_send_date_cf, -- Email Send Date
    from_iso8601_timestamp(nullif(nullif(fields__customfield_10055, 'nan'), 'None')) as date_of_1st_reply_cf, -- Date of 1st Reply
    nullif(nullif(fields__customfield_10056, 'nan'), 'None') as last_commenter_cf, -- Last commenter
    nullif(nullif(fields__customfield_10057, 'nan'), 'None') as last_comment_by_customer_cf, -- Last comment by Customer
    nullif(nullif(fields__customfield_16953, 'nan'), 'None') as zoom_id_cf, -- Zoom ID
    cast(json_parse(nullif(nullif(fields__customfield_14655, 'nan'), 'None')) as array(row("self" varchar, "disabled" boolean, "id" varchar, "value" varchar))) as product_cf, -- Product
    cast(json_parse(nullif(nullif(fields__customfield_16262, 'nan'), 'None')) as array(row("self" varchar, "disabled" boolean, "id" varchar, "value" varchar))) as products_cf, -- Products
    nullif(nullif(fields__customfield_16261, 'nan'), 'None') as ticket_review_details_cf, -- Ticket Review Details
    nullif(nullif(fields__customfield_17470, 'nan'), 'None') as urgency_cf, -- Urgency
    nullif(nullif(fields__customfield_16260, 'nan'), 'None') as ticket_review_cf, -- Ticket Review
    nullif(nullif(fields__customfield_17476, 'nan'), 'None') as investigation_reason_cf, -- Investigation reason
    nullif(nullif(fields__customfield_21055, 'nan'), 'None') as implementer_cf, -- Implementer
    try(cast(nullif(nullif(fields__customfield_21054, 'nan'), 'None') as double)) as minutes_in_current_status_cf, -- Minutes in current status
    nullif(nullif(fields__customfield_17474, 'nan'), 'None') as operational_categorization_cf, -- Operational categorization
    nullif(nullif(fields__customfield_17473, 'nan'), 'None') as product_categorization_cf, -- Product categorization
    nullif(nullif(fields__customfield_10040, 'nan'), 'None') as estimate_cf, -- Estimate
    cast(json_parse(nullif(nullif(fields__customfield_15851, 'nan'), 'None')) as array(varchar)) as organizations_cf, -- Organizations
    nullif(nullif(fields__customfield_17479, 'nan'), 'None') as time_to_close_after_resolution_cf, -- Time to close after resolution
    nullif(nullif(fields__customfield_13550, 'nan'), 'None') as account_cf, -- Account
    nullif(nullif(fields__customfield_15850, 'nan'), 'None') as development_cf, -- Development
    nullif(nullif(fields__customfield_13552, 'nan'), 'None') as case_cf, -- Case
    nullif(nullif(fields__customfield_10166, 'nan'), 'None') as tests_written_cf, -- Tests Written
    nullif(nullif(fields__customfield_10951, 'nan'), 'None') as driver_changes_cf, -- Driver Changes
    nullif(nullif(fields__customfield_20754, 'nan'), 'None') as ts_team_cf, -- TS Team
    cast(json_parse(nullif(nullif(fields__customfield_20755, 'nan'), 'None')) as array(varchar)) as upstream_fixversions_cf, -- Upstream Fixversions
    nullif(nullif(fields__customfield_20752, 'nan'), 'None') as effort_cf, -- Effort
    nullif(nullif(fields__customfield_20753, 'nan'), 'None') as confidence_cf, -- Confidence
    nullif(nullif(fields__customfield_20750, 'nan'), 'None') as reach_cf, -- Reach
    nullif(nullif(fields__customfield_20751, 'nan'), 'None') as impact_cf, -- Impact
    nullif(nullif(fields__customfield_20078, 'nan'), 'None') as auto_close_cf, -- Auto-Close
    nullif(nullif(fields__customfield_17465, 'nan'), 'None') as change_type_cf, -- Change type
    nullif(nullif(fields__customfield_17463, 'nan'), 'None') as pending_reason_cf, -- Pending reason
    cast(json_parse(nullif(nullif(fields__customfield_16252, 'nan'), 'None')) as array(varchar)) as failure_type_cf, -- Failure Type
    from_iso8601_timestamp(nullif(nullif(fields__customfield_17469, 'nan'), 'None')) as change_completion_date_cf, -- Change completion date
    cast(json_parse(nullif(nullif(fields__customfield_12451, 'nan'), 'None')) as array(row("archived" boolean, "releaseDate" varchar, "name" varchar, "description" varchar, "self" varchar, "id" varchar, "released" boolean))) as backport_completed_cf, -- Backport Completed
    from_iso8601_timestamp(nullif(nullif(fields__customfield_17468, 'nan'), 'None')) as change_start_date_cf, -- Change start date
    cast(json_parse(nullif(nullif(fields__customfield_12450, 'nan'), 'None')) as array(row("self" varchar, "disabled" boolean, "id" varchar, "value" varchar))) as backport_requested_cf, -- Backport Requested
    cast(json_parse(nullif(nullif(fields__customfield_14873, 'nan'), 'None')) as array(row("self" varchar, "disabled" boolean, "id" varchar, "value" varchar))) as external_reviewer_cf, -- External Reviewer
    nullif(nullif(fields__customfield_10031, 'nan'), 'None') as operating_system_cf, -- Operating System
    nullif(nullif(fields__customfield_17467, 'nan'), 'None') as change_reason_cf, -- Change reason
    try(cast(nullif(nullif(fields__customfield_16257, 'nan'), 'None') as double)) as pending_lgtm_cf, -- Pending LGTM
    nullif(nullif(fields__customfield_10032, 'nan'), 'None') as operating_system_cf, -- Operating System
    nullif(nullif(fields__customfield_17466, 'nan'), 'None') as change_risk_cf, -- Change risk
    try(cast(nullif(nullif(fields__customfield_18555, 'nan'), 'None') as double)) as _of_sprints_cf, -- # of Sprints
    nullif(nullif(fields__customfield_14876, 'nan'), 'None') as docs_reviewer_cf, -- Docs Reviewer
    cast(json_parse(nullif(nullif(fields__customfield_14995, 'nan'), 'None')) as array(row("self" varchar, "disabled" boolean, "id" varchar, "value" varchar))) as approvers_cf, -- Approvers
    cast(json_parse(nullif(nullif(fields__customfield_14996, 'nan'), 'None')) as array(row("self" varchar, "disabled" boolean, "id" varchar, "value" varchar))) as cloud_access_approvers_cf, -- Cloud Access Approvers
    nullif(nullif(fields__customfield_17450, 'nan'), 'None') as rfslaindex_cf, -- rfSlaIndex
    nullif(nullif(fields__customfield_15150, 'nan'), 'None') as release_notes_cf, -- Release Notes
    cast(json_parse(nullif(nullif(fields__customfield_17453, 'nan'), 'None')) as array(row("self" varchar, "disabled" boolean, "id" varchar, "value" varchar))) as approvers_to_delete__cf, -- Approvers (To Delete)
    cast(json_parse(nullif(nullif(fields__customfield_20063, 'nan'), 'None')) as array(varchar)) as tags_cf, -- Tags
    nullif(nullif(fields__customfield_11350, 'nan'), 'None') as rationale_cf, -- Rationale
    nullif(nullif(fields__customfield_13653, 'nan'), 'None') as detailed_project_statuses_cf, -- Detailed Project Statuses
    try(cast(nullif(nullif(fields__customfield_16350, 'nan'), 'None') as double)) as count_of_linked_failures_cf, -- Count of Linked Failures
    nullif(nullif(fields__customfield_14050, 'nan'), 'None') as team_cf, -- Team
    nullif(nullif(fields__customfield_14051, 'nan'), 'None') as parent_link_cf, -- Parent Link
    cast(json_parse(nullif(nullif(fields__customfield_20176, 'nan'), 'None')) as array(row("self" varchar, "disabled" boolean, "id" varchar, "value" varchar))) as ts_initiative_how_do_we_do_it__cf, -- TS Initiative - How do we do it?
    cast(json_parse(nullif(nullif(fields__customfield_20177, 'nan'), 'None')) as array(row("self" varchar, "disabled" boolean, "id" varchar, "value" varchar))) as ts_initiative_what_we_do__cf, -- TS Initiative - What we do?
    nullif(nullif(fields__customfield_20175, 'nan'), 'None') as ts_initiative_status_cf, -- TS Initiative Status
    nullif(nullif(fields__customfield_12550, 'nan'), 'None') as rank_cf, -- Rank
    cast(json_parse(nullif(nullif(fields__customfield_14851, 'nan'), 'None')) as array(varchar)) as first_failing_revision_cf, -- First Failing Revision
    cast(json_parse(nullif(nullif(fields__customfield_12551, 'nan'), 'None')) as array(row("emailAddress" varchar, "avatarUrls" map(varchar, varchar), "displayName" varchar, "name" varchar, "timeZone" varchar, "self" varchar, "active" boolean, "key" varchar))) as request_participants_cf, -- Request participants
    nullif(nullif(fields__customfield_10011, 'nan'), 'None') as backwards_compatibility_cf, -- Backwards Compatibility
    cast(json_parse(nullif(nullif(fields__customfield_14852, 'nan'), 'None')) as array(varchar)) as fix_revision_cf, -- Fix Revision
    nullif(nullif(fields__customfield_10257, 'nan'), 'None') as documentation_changes_cf, -- Documentation Changes
    nullif(nullif(fields__customfield_20167, 'nan'), 'None') as product_marketing_manager_cf, -- Product Marketing Manager
    nullif(nullif(fields__customfield_20288, 'nan'), 'None') as researching_cf, -- Researching
    nullif(nullif(fields__customfield_20289, 'nan'), 'None') as stalled_cf, -- Stalled
    nullif(nullif(fields__customfield_20287, 'nan'), 'None') as alert_assignee_cf, -- Alert Assignee
    nullif(nullif(fields__customfield_16463, 'nan'), 'None') as time_to_business_approval_request_cf, -- Time to Business Approval Request
    nullif(nullif(fields__customfield_17551, 'nan'), 'None') as requested_completion_planned_completion_cf, -- Requested Completion - Planned Completion
    nullif(nullif(fields__customfield_20283, 'nan'), 'None') as desktop_hardware_specifications_cf, -- Desktop Hardware Specifications
    nullif(nullif(fields__customfield_11450, 'nan'), 'None') as customer_request_type_cf, -- Customer Request Type
    nullif(nullif(fields__customfield_16468, 'nan'), 'None') as website_url_cf, -- Website URL
    nullif(nullif(fields__customfield_16467, 'nan'), 'None') as pending_business_approval_cf, -- Pending Business Approval
    nullif(nullif(fields__customfield_14166, 'nan'), 'None') as branch_cf, -- Branch
    nullif(nullif(fields__customfield_11452, 'nan'), 'None') as time_to_first_response_cf, -- Time to first response
    nullif(nullif(fields__customfield_16466, 'nan'), 'None') as time_to_netsuite_entry_cf, -- Time to Netsuite Entry
    nullif(nullif(fields__customfield_11451, 'nan'), 'None') as time_to_resolution_cf, -- Time to resolution
    try(cast(nullif(nullif(fields__customfield_16465, 'nan'), 'None') as double)) as linked_bf_score_cf, -- Linked BF Score
    nullif(nullif(fields__customfield_10000, 'nan'), 'None') as old_backport_cf, -- Old_Backport
    nullif(nullif(fields__customfield_11453, 'nan'), 'None') as time_waiting_for_support_cf, -- Time waiting for support
    nullif(nullif(fields__customfield_19050, 'nan'), 'None') as waiting_for_it_cf, -- Waiting for IT
    cast(json_parse(nullif(nullif(fields__customfield_20279, 'nan'), 'None')) as array(row("self" varchar, "disabled" boolean, "id" varchar, "value" varchar))) as account_access_for_applications_cf, -- Account Access for Applications
    nullif(nullif(fields__customfield_14270, 'nan'), 'None') as waiting_for_employee_cf, -- Waiting for Employee
    from_iso8601_date(nullif(nullif(fields__customfield_20275, 'nan'), 'None')) as to_delete_end_date_cf, -- To Delete - End date
    nullif(nullif(fields__customfield_20276, 'nan'), 'None') as additional_product_details_requests_cf, -- Additional Product Details/Requests
    nullif(nullif(fields__customfield_20153, 'nan'), 'None') as first_response_time_frt__cf, -- First Response Time (FRT)
    nullif(nullif(fields__customfield_14275, 'nan'), 'None') as close_after_3_days_cf, -- Close After 3 Days
    nullif(nullif(fields__customfield_16452, 'nan'), 'None') as critical_issues_resolved_in_24_hours_cf, -- Critical issues resolved in 24 hours
    nullif(nullif(fields__customfield_20392, 'nan'), 'None') as versioned_api_impact_summary_cf, -- Versioned API Impact Summary
    nullif(nullif(fields__customfield_14272, 'nan'), 'None') as question_sla_cf, -- Question SLA
    from_iso8601_date(nullif(nullif(fields__customfield_20272, 'nan'), 'None')) as to_delete_start_date_cf, -- To Delete - Start date
    nullif(nullif(fields__customfield_16450, 'nan'), 'None') as topology_cf, -- Topology
    cast(json_parse(nullif(nullif(fields__customfield_14278, 'nan'), 'None')) as array(varchar)) as evergreen_project_cf, -- Evergreen Project
    from_iso8601_date(nullif(nullif(fields__customfield_16457, 'nan'), 'None')) as published_cf, -- Published
    nullif(nullif(fields__customfield_20391, 'nan'), 'None') as versioned_api_impact_cf, -- Versioned API Impact
    nullif(nullif(fields__customfield_14276, 'nan'), 'None') as bug_symptoms_cf, -- Bug Symptoms
    try(cast(nullif(nullif(fields__customfield_16455, 'nan'), 'None') as double)) as cvssscore_cf, -- CVSSScore
    cast(json_parse(nullif(nullif(fields__customfield_14277, 'nan'), 'None')) as array(varchar)) as failing_buildvariants_cf, -- Failing Buildvariants
    nullif(nullif(fields__customfield_19162, 'nan'), 'None') as alignment_cf, -- Alignment
    from_iso8601_timestamp(nullif(nullif(fields__customfield_20385, 'nan'), 'None')) as first_occurrence_cf, -- First Occurrence
    try(cast(nullif(nullif(fields__customfield_19950, 'nan'), 'None') as double)) as actual_story_points_cf, -- Actual Story Points
    from_iso8601_timestamp(nullif(nullif(fields__customfield_20386, 'nan'), 'None')) as last_occurrence_cf, -- Last Occurrence
    nullif(nullif(fields__customfield_19951, 'nan'), 'None') as waiting_for_bizsys_cf, -- Waiting for BIZSYS
    nullif(nullif(fields__customfield_18063, 'nan'), 'None') as github__cf, -- GitHub#
    nullif(nullif(fields__customfield_19152, 'nan'), 'None') as waiting_for_vendor_cf, -- Waiting for Vendor
    nullif(nullif(fields__customfield_14263, 'nan'), 'None') as t_shirt_size_cf, -- T-Shirt Size
    try(cast(nullif(nullif(fields__customfield_20384, 'nan'), 'None') as double)) as count_of_linked_bfgs_cf, -- Count of Linked BFGs
    nullif(nullif(fields__customfield_19153, 'nan'), 'None') as waiting_for_approval_cf, -- Waiting for Approval
    nullif(nullif(fields__customfield_14264, 'nan'), 'None') as risk_probability_cf, -- Risk probability
    from_iso8601_date(nullif(nullif(fields__customfield_14261, 'nan'), 'None')) as start_date_cf, -- Start date
    nullif(nullif(fields__customfield_18066, 'nan'), 'None') as concerns_around_backporting_this_change__cf, -- Concerns around backporting this change?
    nullif(nullif(fields__customfield_20382, 'nan'), 'None') as theme_cf, -- Theme
    from_iso8601_date(nullif(nullif(fields__customfield_14262, 'nan'), 'None')) as end_date_cf, -- End date
    nullif(nullif(fields__customfield_14267, 'nan'), 'None') as aha_reference_cf, -- Aha! Reference
    nullif(nullif(fields__customfield_13850, 'nan'), 'None') as triaged_cf, -- Triaged
    nullif(nullif(fields__customfield_14265, 'nan'), 'None') as risk_consequence_cf, -- Risk consequence
    nullif(nullif(fields__customfield_14266, 'nan'), 'None') as documentation_changes_summary_cf, -- Documentation Changes Summary
    nullif(nullif(fields__customfield_19952, 'nan'), 'None') as impact_cf, -- Impact
    nullif(nullif(fields__customfield_19150, 'nan'), 'None') as time_to_resolved_cf, -- Time to Resolved
    nullif(nullif(fields__customfield_19151, 'nan'), 'None') as time_to_closed_cf, -- Time to Closed
    nullif(nullif(fields__customfield_14252, 'nan'), 'None') as backport_approved_by_cf, -- Backport Approved By
    cast(json_parse(nullif(nullif(fields__customfield_14253, 'nan'), 'None')) as array(row("self" varchar, "disabled" boolean, "id" varchar, "value" varchar))) as required_lgtms_cf, -- Required LGTMs
    nullif(nullif(fields__customfield_14251, 'nan'), 'None') as environment_cf, -- Environment
    nullif(nullif(fields__customfield_12750, 'nan'), 'None') as external_issue_id_cf, -- External issue ID
    nullif(nullif(fields__customfield_14254, 'nan'), 'None') as product_rank_cf, -- Product Rank
    nullif(nullif(fields__customfield_14255, 'nan'), 'None') as customer_case_link_cf, -- Customer Case Link
    cast(json_parse(nullif(nullif(fields__customfield_12751, 'nan'), 'None')) as array(row("self" varchar, "disabled" boolean, "id" varchar, "value" varchar))) as assigned_teams_cf, -- Assigned Teams
    from_iso8601_date(nullif(nullif(fields__customfield_14258, 'nan'), 'None')) as baseline_start_date_cf, -- Baseline start date
    from_iso8601_date(nullif(nullif(fields__customfield_14259, 'nan'), 'None')) as baseline_end_date_cf, -- Baseline end date
    nullif(nullif(fields__customfield_13954, 'nan'), 'None') as code_etiquette_cf, -- Code Etiquette
    nullif(nullif(fields__customfield_13956, 'nan'), 'None') as escalation_sla_cf, -- Escalation SLA
    cast(json_parse(nullif(nullif(fields__customfield_13150, 'nan'), 'None')) as array(row("self" varchar, "disabled" boolean, "id" varchar, "value" varchar))) as lgtm_cf, -- LGTM
    nullif(nullif(fields__customfield_17755, 'nan'), 'None') as type_of_work_tstools__cf, -- Type Of Work (TSTOOLS)
    try(cast(nullif(nullif(fields__customfield_10555, 'nan'), 'None') as double)) as story_points_cf, -- Story Points
    try(cast(nullif(nullif(fields__customfield_10556, 'nan'), 'None') as double)) as business_value_cf, -- Business Value
    cast(json_parse(nullif(nullif(fields__customfield_10557, 'nan'), 'None')) as array(varchar)) as sprint_cf, -- Sprint
    nullif(nullif(fields__customfield_10558, 'nan'), 'None') as rank_obsolete__cf, -- Rank (Obsolete)
    nullif(nullif(fields__customfield_10559, 'nan'), 'None') as release_version_history_cf, -- Release Version History
    nullif(nullif(fields__customfield_20358, 'nan'), 'None') as contractor_request_type_link_jira_proc_tickets_cf, -- Contractor Request Type-Link Jira Proc Tickets
    nullif(nullif(fields__customfield_20359, 'nan'), 'None') as average_wait_time_awt__cf, -- Average Wait Time (AWT)
    from_iso8601_date(nullif(nullif(fields__customfield_18950, 'nan'), 'None')) as target_start_cf, -- Target start
    try(cast(nullif(nullif(fields__customfield_16651, 'nan'), 'None') as double)) as number_of_vulnerable_servers_cf, -- Number of Vulnerable Servers
    nullif(nullif(fields__customfield_14352, 'nan'), 'None') as time_to_closed_cf, -- Time to closed
    nullif(nullif(fields__customfield_14350, 'nan'), 'None') as serverrank_cf, -- serverRank
    nullif(nullif(fields__customfield_14355, 'nan'), 'None') as estimated_time_to_complete_cf, -- Estimated Time to Complete
    nullif(nullif(fields__customfield_18955, 'nan'), 'None') as waiting_for_user_input_cf, -- Waiting for User Input
    nullif(nullif(fields__customfield_12055, 'nan'), 'None') as document_url_cf, -- Document URL
    cast(json_parse(nullif(nullif(fields__customfield_14356, 'nan'), 'None')) as array(row("self" varchar, "disabled" boolean, "id" varchar, "value" varchar))) as server_feature_testability_status_cf, -- Server Feature Testability Status
    nullif(nullif(fields__customfield_14353, 'nan'), 'None') as customer_name_cf, -- Customer Name
    nullif(nullif(fields__customfield_14354, 'nan'), 'None') as create_help_tickets_via_portal_cf, -- Create HELP Tickets Via Portal
    from_iso8601_date(nullif(nullif(fields__customfield_10550, 'nan'), 'None')) as planned_start_cf, -- Planned Start
    cast(json_parse(nullif(nullif(fields__customfield_16652, 'nan'), 'None')) as array(row("self" varchar, "disabled" boolean, "id" varchar, "value" varchar))) as mongodb_version_cf, -- MongoDB Version
    from_iso8601_date(nullif(nullif(fields__customfield_18951, 'nan'), 'None')) as target_end_cf, -- Target end
    from_iso8601_date(nullif(nullif(fields__customfield_10551, 'nan'), 'None')) as planned_end_cf, -- Planned End
    nullif(nullif(fields__customfield_12850, 'nan'), 'None') as external_issue_id_cf, -- External issue ID
    try(cast(nullif(nullif(fields__customfield_18952, 'nan'), 'None') as double)) as original_story_points_cf, -- Original story points
    cast(json_parse(nullif(nullif(fields__customfield_10553, 'nan'), 'None')) as array(row("self" varchar, "disabled" boolean, "id" varchar, "value" varchar))) as flagged_cf, -- Flagged
    nullif(nullif(fields__customfield_18954, 'nan'), 'None') as waiting_for_reporter_test__cf, -- Waiting for Reporter (Test)
    cast(json_parse(nullif(nullif(fields__customfield_10554, 'nan'), 'None')) as array(varchar)) as epic_theme_cf, -- Epic/Theme
    cast(json_parse(nullif(nullif(fields__customfield_19475, 'nan'), 'None')) as array(varchar)) as cloud_provider_cf, -- Cloud Provider
    nullif(nullif(fields__customfield_18265, 'nan'), 'None') as launch_plan_cf, -- Launch Plan
    nullif(nullif(fields__customfield_17052, 'nan'), 'None') as downstream_changes_summary_cf, -- Downstream Changes Summary
    cast(json_parse(nullif(nullif(fields__customfield_20463, 'nan'), 'None')) as array(row("self" varchar, "disabled" boolean, "id" varchar, "value" varchar))) as severity_type_cf, -- Severity Type
    cast(json_parse(nullif(nullif(fields__customfield_17051, 'nan'), 'None')) as array(row("self" varchar, "disabled" boolean, "id" varchar, "value" varchar))) as teams_impacted_cf, -- Teams Impacted
    try(cast(nullif(nullif(fields__customfield_15550, 'nan'), 'None') as double)) as score_cf, -- Score
    from_iso8601_date(nullif(nullif(fields__customfield_18263, 'nan'), 'None')) as cloud_dev_target_cf, -- Cloud-Dev Target
    cast(json_parse(nullif(nullif(fields__customfield_19474, 'nan'), 'None')) as array(varchar)) as atlas_hostnames_cf, -- Atlas Hostnames
    nullif(nullif(fields__customfield_18264, 'nan'), 'None') as feature_flag_cf, -- Feature Flag
    nullif(nullif(fields__customfield_19353, 'nan'), 'None') as time_to_security_review_cf, -- Time to Security Review
    nullif(nullif(fields__customfield_11750, 'nan'), 'None') as reviewer_cf, -- Reviewer
    cast(json_parse(nullif(nullif(fields__customfield_11864, 'nan'), 'None')) as array(row("self" varchar, "disabled" boolean, "id" varchar, "value" varchar))) as lgtm_kernel_or_field__cf, -- LGTM (Kernel or Field)
    nullif(nullif(fields__customfield_17050, 'nan'), 'None') as downstream_team_attention_cf, -- Downstream Team Attention
    nullif(nullif(fields__customfield_20455, 'nan'), 'None') as os_cve_completion_due_date_cf, -- OS CVE Completion Due Date
    from_iso8601_timestamp(nullif(nullif(fields__customfield_19464, 'nan'), 'None')) as team_assignment_cf, -- Team Assignment
    nullif(nullif(fields__customfield_18254, 'nan'), 'None') as dependencies_cf, -- Dependencies
    nullif(nullif(fields__customfield_19465, 'nan'), 'None') as cluster_link_cf, -- Cluster Link
    cast(json_parse(nullif(nullif(fields__customfield_19466, 'nan'), 'None')) as array(varchar)) as nodenames_cf, -- Nodenames
    nullif(nullif(fields__customfield_14450, 'nan'), 'None') as approvals_cf, -- Approvals
    nullif(nullif(fields__customfield_20450, 'nan'), 'None') as external_issue_id_cf, -- External issue ID
    nullif(nullif(fields__customfield_14451, 'nan'), 'None') as satisfaction_cf, -- Satisfaction
    nullif(nullif(fields__customfield_19463, 'nan'), 'None') as from_email_address_cf, -- From Email Address
    from_iso8601_timestamp(nullif(nullif(fields__customfield_14452, 'nan'), 'None')) as satisfaction_date_cf, -- Satisfaction date
    cast(json_parse(nullif(nullif(fields__customfield_12950, 'nan'), 'None')) as array(varchar)) as failing_tasks_cf, -- Failing Tasks
    nullif(nullif(fields__customfield_11861, 'nan'), 'None') as user_summary_cf, -- User Summary
    nullif(nullif(fields__customfield_11863, 'nan'), 'None') as field_reviewer_cf, -- Field Reviewer
    nullif(nullif(fields__customfield_11862, 'nan'), 'None') as kernel_reviewer_cf, -- Kernel Reviewer
    nullif(nullif(fields__customfield_11856, 'nan'), 'None') as boost_version_cf, -- Boost Version
    nullif(nullif(fields__customfield_17959, 'nan'), 'None') as github_url_cf, -- Github URL
    nullif(nullif(fields__customfield_17958, 'nan'), 'None') as time_to_regional_response_cf, -- Time to regional response
    nullif(nullif(fields__customfield_18360, 'nan'), 'None') as product_design_cf, -- Product Design
    nullif(nullif(fields__customfield_18361, 'nan'), 'None') as docs_owner_cf, -- Docs Owner
    cast(json_parse(nullif(nullif(fields__customfield_15650, 'nan'), 'None')) as array(row("self" varchar, "disabled" boolean, "id" varchar, "value" varchar))) as reviewers_cf, -- Reviewers
    nullif(nullif(fields__customfield_18362, 'nan'), 'None') as engineering_lead_cf, -- Engineering Lead
    cast(json_parse(nullif(nullif(fields__customfield_19451, 'nan'), 'None')) as array(varchar)) as revision_order_number_cf, -- Revision Order Number
    nullif(nullif(fields__customfield_15654, 'nan'), 'None') as nessus_see_also_cf, -- Nessus See Also
    nullif(nullif(fields__customfield_17952, 'nan'), 'None') as uservoice_links_cf, -- UserVoice Links
    nullif(nullif(fields__customfield_15651, 'nan'), 'None') as nessus_plugin_id_cf, -- Nessus Plugin ID
    from_iso8601_timestamp(nullif(nullif(fields__customfield_19458, 'nan'), 'None')) as wfbf_date_cf, -- WFBF Date
    nullif(nullif(fields__customfield_15655, 'nan'), 'None') as nessus_cvss_cf, -- Nessus CVSS
    nullif(nullif(fields__customfield_15656, 'nan'), 'None') as nessus_cve_cf -- Nessus CVE
from
    awsdatacatalog.raw_jira.dw__jira__issues
