-- This file generated by generate.py.

-- <yaml>
-- DependsOn: {}
-- </yaml>
SELECT  CAST(vs."_id" AS VARCHAR)  AS "_id",
        vs."date"                  AS "date",
        vs."has_versions"          AS "has_versions",
        vs."pct_green"             AS "pct_green",
        vs."project"               AS "project",
        vs."task_records"          AS "task_records"
        -- <COMMON_ETL_FIELDS>
        , LOCALTIMESTAMP AS "_extract_timestamp"
        -- </COMMON_ETL_FIELDS>
FROM  "tpm_build_failures_atlas"."evergreen_data"."task_stats" AS vs

