-- This file generated by generate.py.

-- <yaml>
-- DependsOn: {}
-- </yaml>
SELECT  CAST(vs."_id" AS VARCHAR)  AS "_id",
        vs."branch"                AS "branch",
        vs."repo"                  AS "repo",
        vs."revert_commit"         AS "revert_commit",
        vs."reverted_commit"       AS "reverted_commit",
        vs."ticket"                AS "ticket",
        vs."time_reverted"         AS "time_reverted"
        -- <COMMON_ETL_FIELDS>
        , LOCALTIMESTAMP AS "_extract_timestamp"
        -- </COMMON_ETL_FIELDS>
FROM  "dev_prod_build_baron_atlas"."auto_revert"."reverts" AS vs

