-- This file generated by generate.py.

-- <yaml>
-- DependsOn: {}
-- </yaml>
SELECT  CAST(vs."_id" AS VARCHAR)  AS "_id",
        vs."auth_user"             AS "auth_user",
        vs."new_rule"              AS "new_rule",
        vs."previous_rule"         AS "previous_rule",
        vs."timestamp"             AS "timestamp"
        -- <COMMON_ETL_FIELDS>
        , LOCALTIMESTAMP AS "_extract_timestamp"
        -- </COMMON_ETL_FIELDS>
FROM  dev_prod_build_baron_atlas.buildbaron.bfg_contexts_audit AS vs

