-- This file generated by generate.py.

-- <yaml>
-- DependsOn: {}
-- </yaml>
SELECT  CAST(vs."_id" AS VARCHAR)  AS "_id",
        vs."active"                AS "active",
        vs."bf_key"                AS "bf_key",
        vs."context"               AS "context",
        vs."created_date"          AS "created_date",
        vs."expiration"            AS "expiration",
        vs."resolution"            AS "resolution",
        vs."rules"                 AS "rules",
        vs."user_id"               AS "user_id"
        -- <COMMON_ETL_FIELDS>
        , LOCALTIMESTAMP AS "_extract_timestamp"
        -- </COMMON_ETL_FIELDS>
FROM  dev_prod_build_baron_atlas.buildbaron.auto_resolution_rules AS vs

