-- This file generated by generate.py.

-- <yaml>
-- DependsOn: {}
-- </yaml>
SELECT  CAST(vs."_id" AS VARCHAR)  AS "_id",
        vs."build_id"              AS "build_id",
        vs."build_variant"         AS "build_variant",
        vs."date_created"          AS "date_created",
        vs."display_name"          AS "display_name",
        vs."execution"             AS "execution",
        vs."order"                 AS "order",
        vs."project_id"            AS "project_id",
        vs."status"                AS "status",
        vs."status_details"        AS "status_details",
        vs."task_id"               AS "task_id",
        vs."version_id"            AS "version_id"
        -- <COMMON_ETL_FIELDS>
        , LOCALTIMESTAMP AS "_extract_timestamp"
        -- </COMMON_ETL_FIELDS>
FROM  "dev_prod_build_baron_atlas"."auto_revert"."failed_tasks" AS vs

