-- This file generated by generate.py.

-- <yaml>
-- DependsOn: {}
-- </yaml>
SELECT  CAST(vs."_id" AS VARCHAR)  AS "_id",
        vs."created"               AS "created",
        vs."key"                   AS "key",
        vs."resolved"              AS "resolved",
        vs."status"                AS "status",
        vs."summary"               AS "summary",
        vs."symptom"               AS "symptom",
        vs."updated"               AS "updated"
        -- <COMMON_ETL_FIELDS>
        , LOCALTIMESTAMP AS "_extract_timestamp"
        -- </COMMON_ETL_FIELDS>
FROM  "dev_prod_build_baron_atlas"."buildbaron"."bfs" AS vs

