-- This file generated by generate.py.

-- <yaml>
-- DependsOn: {}
-- </yaml>
SELECT  CAST(vs."_id" AS VARCHAR)     AS "_id",
        vs."bfg_auto_resolve_age"     AS "bfg_auto_resolve_age",
        vs."bfg_auto_resolve_status"  AS "bfg_auto_resolve_status",
        vs."triage_context"           AS "triage_context"
        -- <COMMON_ETL_FIELDS>
        , LOCALTIMESTAMP AS "_extract_timestamp"
        -- </COMMON_ETL_FIELDS>
FROM  "dev_prod_build_baron_atlas"."buildbaron"."bfg_context_attributes" AS vs

